# Generated by Django 4.2 on 2023-05-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackagingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packaging_component_name", models.CharField(max_length=1000)),
                (
                    "packaging_component_id",
                    models.CharField(max_length=1000, unique=True),
                ),
                ("packaging_component_category", models.CharField(max_length=1000)),
                (
                    "packaging_component_lead_time",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "packaging_component_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "packaging_component_type",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("product_image", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SubProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sp_name", models.CharField(max_length=1000)),
                ("sp_image", models.CharField(max_length=1000)),
                ("sp_leadtime", models.IntegerField(blank=True, null=True)),
                ("sp_manfcost", models.IntegerField(blank=True, null=True)),
                ("sp_sku", models.CharField(max_length=1000, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_products",
                        to="ecomdash.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sales", models.DateTimeField()),
                ("quantity_sold", models.IntegerField(default=0)),
                ("sales_channel", models.CharField(max_length=1000)),
                ("sales_type", models.CharField(max_length=1000)),
                ("product_return", models.BooleanField(default=False)),
                (
                    "sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_available", models.IntegerField(default=0)),
                ("last_inventory_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_product_inventory",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackagingComponentInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pc_inventory_available", models.IntegerField(default=0)),
                (
                    "pc_last_inventory_checked",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "packaging_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_inventory",
                        to="ecomdash.packagingcomponent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="packagingcomponent",
            name="sub_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packaging_components",
                to="ecomdash.subproduct",
            ),
        ),
        migrations.CreateModel(
            name="BatchID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manf_date", models.DateField(blank=True, null=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=1000)),
                (
                    "sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_ids",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
    ]
