# Generated by Django 4.2 on 2023-06-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0003_rename_name_saleschannel_sales_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchid",
            name="batchname",
            field=models.CharField(default="DEBatchName", max_length=1000),
        ),
    ]
