# Generated by Django 4.2 on 2023-06-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0004_batchid_batchname"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproduct",
            name="packaging_components",
            field=models.ManyToManyField(
                related_name="sub_products", to="ecomdash.packagingcomponent"
            ),
        ),
        migrations.AlterField(
            model_name="packagingcomponent",
            name="sub_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packaging_components_set",
                to="ecomdash.subproduct",
            ),
        ),
    ]
