# Generated by Django 4.2 on 2023-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0005_subproduct_packaging_components_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagingcomponent",
            name="sub_product",
        ),
        migrations.AddField(
            model_name="packagingcomponent",
            name="sub_product",
            field=models.ManyToManyField(
                related_name="packaging_components_set", to="ecomdash.subproduct"
            ),
        ),
    ]
