# Generated by Django 4.2 on 2023-06-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0006_remove_packagingcomponent_sub_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagingcomponent",
            name="sub_product",
        ),
    ]
