# Generated by Django 4.2 on 2023-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0007_remove_packagingcomponent_sub_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="order_id",
            field=models.CharField(default="DE101", max_length=1000),
        ),
    ]
