# Generated by Django 4.2 on 2023-06-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0008_productsale_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsale",
            name="order_id",
        ),
    ]
