# Generated by Django 4.2 on 2023-07-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0010_productsale_orderid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sales", models.DateTimeField()),
                ("quantity_sold", models.IntegerField(default=0)),
                ("product_return", models.BooleanField(default=False)),
                ("orderid", models.CharField(default="DE101", max_length=1000)),
                ("sub_product_barcode", models.CharField(max_length=1000, null=True)),
                ("sub_product_gst", models.CharField(default="18", max_length=1000)),
                (
                    "sales_channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="ecomdash.saleschannel",
                    ),
                ),
                (
                    "sales_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecomdash.salestype",
                    ),
                ),
                (
                    "sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="ProductInventory",
            new_name="SubProductInventory",
        ),
        migrations.DeleteModel(
            name="ProductSale",
        ),
    ]
