# Generated by Django 4.2 on 2023-07-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0011_subproductsale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchname", models.CharField(default="DEBatchName", max_length=1000)),
                ("manf_date", models.DateField(blank=True, null=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="BatchProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_product_batch_inventory", models.IntegerField()),
                (
                    "batchdetail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomdash.batchdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="subproductsale",
            name="sub_product_barcode",
        ),
        migrations.RemoveField(
            model_name="subproductsale",
            name="sub_product_gst",
        ),
        migrations.AddField(
            model_name="subproduct",
            name="sp_barcode",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="subproduct",
            name="sp_cost",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="subproduct",
            name="sp_gst",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name="BatchID",
        ),
        migrations.AddField(
            model_name="batchproduct",
            name="sub_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecomdash.subproduct"
            ),
        ),
        migrations.AddField(
            model_name="batchdetail",
            name="sub_product",
            field=models.ManyToManyField(
                through="ecomdash.BatchProduct", to="ecomdash.subproduct"
            ),
        ),
        migrations.AddField(
            model_name="subproduct",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecomdash.manufacturer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchproduct",
            unique_together={("sub_product", "batchdetail")},
        ),
    ]
