# Generated by Django 4.2 on 2023-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0012_batchdetail_batchproduct_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subproduct",
            name="sp_sku",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
