# Generated by Django 4.2 on 2023-07-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0014_kit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subproduct",
            old_name="sp_cost",
            new_name="sp_price",
        ),
    ]
