# Generated by Django 4.2 on 2023-07-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0015_rename_sp_cost_subproduct_sp_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subproductsale",
            old_name="orderid",
            new_name="amazon_orderid",
        ),
        migrations.CreateModel(
            name="ShopifySubProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shopify_date_of_sales", models.DateTimeField()),
                ("shopify_quantity_sold", models.IntegerField(default=0)),
                ("shopify_product_return", models.BooleanField(default=False)),
                (
                    "shopify_merchant_ordername",
                    models.CharField(default="DE101", max_length=1000),
                ),
                ("shopify_default_order_id", models.IntegerField()),
                (
                    "shopify_gross_sales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shopify_productsale_taxes",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "shopify_productsale_discount",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "sales_channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopifysales",
                        to="ecomdash.saleschannel",
                    ),
                ),
                (
                    "sales_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecomdash.salestype",
                    ),
                ),
                (
                    "shopify_sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopifysubproductsales",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
    ]
