# Generated by Django 4.2 on 2023-07-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0017_alter_shopifysubproductsale_shopify_default_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifysubproductsale",
            name="shopify_productsale_discount",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="shopifysubproductsale",
            name="shopify_productsale_taxes",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="sp_gst",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="sp_price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
