# Generated by Django 4.2 on 2023-07-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecomdash",
            "0018_alter_shopifysubproductsale_shopify_productsale_discount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KitSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sale", models.DateTimeField()),
                ("quantity_sold", models.IntegerField(default=0)),
                (
                    "kit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kitsales",
                        to="ecomdash.kit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_inventory", models.IntegerField()),
                ("updated_inventory", models.IntegerField()),
                ("quantity_sold", models.IntegerField()),
                ("order_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_logs",
                        to="ecomdash.subproduct",
                    ),
                ),
            ],
        ),
    ]
