# Generated by Django 4.2 on 2023-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0019_kitsale_inventorylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitsale",
            name="shopify_default_order_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
