# Generated by Django 4.2 on 2023-07-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0022_amazonsubproductsale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonKitSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sale", models.DateTimeField()),
                ("amazon_quantity_sold", models.IntegerField(default=0)),
                ("amazon_order_id", models.BigIntegerField(default=0)),
                (
                    "kit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amazonkitsales",
                        to="ecomdash.kit",
                    ),
                ),
            ],
        ),
    ]
