# Generated by Django 4.2 on 2023-07-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0024_remove_amazonkitsale_amazon_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingComponentInventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_inventory", models.IntegerField()),
                ("updated_inventory", models.IntegerField()),
                ("quantity_sold", models.IntegerField()),
                ("order_id", models.CharField(blank=True, max_length=50, null=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "packaging_component",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_inventory_logs",
                        to="ecomdash.packagingcomponent",
                    ),
                ),
            ],
        ),
    ]
