# Generated by Django 4.2 on 2023-07-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0025_packagingcomponentinventorylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amazonsubproductsale",
            name="amazon_orderid",
            field=models.CharField(default="AMZ101", max_length=50),
        ),
        migrations.AlterField(
            model_name="batchdetail",
            name="batchname",
            field=models.CharField(default="DEBatchName", max_length=200),
        ),
        migrations.AlterField(
            model_name="packagingcomponentinventory",
            name="packaging_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pc_inventory",
                to="ecomdash.packagingcomponent",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subproductinventory",
            name="sub_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_product_inventory",
                to="ecomdash.subproduct",
                unique=True,
            ),
        ),
    ]
