# Generated by Django 4.2 on 2023-07-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomdash", "0026_alter_amazonsubproductsale_amazon_orderid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingcomponent",
            name="packaging_component_category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="packagingcomponent",
            name="packaging_component_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="packagingcomponent",
            name="packaging_component_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="packagingcomponent",
            name="packaging_component_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="packagingcomponentinventory",
            name="packaging_component",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pc_inventory",
                to="ecomdash.packagingcomponent",
            ),
        ),
        migrations.AlterField(
            model_name="subproductinventory",
            name="sub_product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_product_inventory",
                to="ecomdash.subproduct",
            ),
        ),
    ]
