# Generated by Django 4.2 on 2023-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecomdash",
            "0027_alter_packagingcomponent_packaging_component_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="saleschannel",
            name="treat_negative_sales_as_returns",
            field=models.BooleanField(default=True),
        ),
    ]
