default_context:
  _pegasus_version: '2024.1'
  author_name: Vasu
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: none
  description: The most amazing SaaS application the world has ever seen
  docker_setup: default
  domain_name: localhost:8000
  email: vasu@sellerlift.com
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: test-everything
  project_slug: test_aassaasa
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_impersonation: y
  use_openai: n
  use_sentry: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
